# Generated by Django 5.0.4 on 2024-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('background', models.FileField(upload_to='events', verbose_name='Фон')),
                ('duration', models.CharField(max_length=255, verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=25, verbose_name='Тип мероприятия')),
            ],
        ),
    ]
