# Generated by Django 5.0.4 on 2024-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_en_event_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
