# Generated by Django 5.0.4 on 2024-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_page_news',
            old_name='image_1',
            new_name='news_1',
        ),
        migrations.RenameField(
            model_name='main_page_news',
            old_name='image_2',
            new_name='news_2',
        ),
        migrations.RenameField(
            model_name='main_page_news',
            old_name='image_3',
            new_name='news_3',
        ),
        migrations.RenameField(
            model_name='main_page_news',
            old_name='image_4',
            new_name='news_4',
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='заголовок'),
        ),
    ]
