# Generated by Django 5.0.4 on 2024-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_image_1_main_page_news_news_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заголовок'),
        ),
    ]
