# Generated by Django 5.0.4 on 2024-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_of_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('role', models.CharField(max_length=100, verbose_name='Должность')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('number', 'Number'), ('email', 'Email'), ('address', 'Address'), ('extra number', 'Extra Number')], max_length=20, verbose_name='Тип')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Email_sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.EmailField(max_length=254, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Получатель вопросов',
                'verbose_name_plural': 'Получатель вопросов',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.CreateModel(
            name='Images_for_multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images_for_multimedia', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(max_length=500, verbose_name='Ссылка на видео')),
                ('type', models.CharField(choices=[('graduates', 'Graduates'), ('video', 'Video'), ('picture', 'Picture')], max_length=20, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('avatar', models.FileField(upload_to='avatars', verbose_name='Фотография')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('bio', models.TextField(verbose_name='Информация')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='samples', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='sertificates', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
