# Generated by Django 5.0.4 on 2024-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_information',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ky',
            field=models.TextField(null=True, verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='Био'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
