# Generated by Django 5.0.4 on 2024-08-31 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0002_alter_contact_information_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
