# Generated by Django 5.0.4 on 2024-07-30 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_alter_block_of_contact_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_information',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact_information',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
