# Generated by Django 5.0.4 on 2024-07-30 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0005_alter_sample_description_alter_sample_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='bio_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
