# Generated by Django 5.0.4 on 2024-06-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_remove_specialtie_mini_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_programms',
            name='image',
            field=models.FileField(default=1, upload_to='courses_and_programms', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
