# Generated by Django 5.0.4 on 2024-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_courses_programms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_programms',
            name='image',
            field=models.FileField(upload_to='coursesProgramms', verbose_name='Файл'),
        ),
    ]
